### ISSUE TITLE
Talking about Thinky

### ISSUE THREAD

**Issue by Shenrak** [ShinGecko/neKo-Api#4]
How exactly should I get the result ?
```javascript
let auth = async (email, password) => {
  let result
  models.users.filter({
    email: email,
    password: password,
  }).run().then(user => result = user)
  return result
}

module.exports.auth = async function (ctx) {
  console.log(auth(ctx.request.body.email, ctx.request.body.password))
  if (auth(ctx.request.body.email, ctx.request.body.password)) {
    ctx.status = 200
  } else {
    ctx.set('Content-Type', 'text/plain')
    ctx.status = 401
    ctx.body = 'Wrong Login or Password'
  }
  return true
}
```

I know it's asynchronous so actually I'm wondering how i should get chat's in the .then(user) callback

**Comment by justinrlle** [comment]
Two things: about _auth_, and how to use it.

### _auth_
Because it's asynchronous, the moment you do `return result` isn't guaranteed to be after the `.then`.
you can do two things here:
- you return the promise (and no `async` on the function)
```javascript
let auth = (email, password) => {
  return models.users.filter({
    email: email,
    password: password,
  }).run()
}
```
- you `await` on the promise (and mark `async`)
```javascript
let auth = async (email, password) => {
  return await models.users.filter({
    email: email,
    password: password,
  }).run()
}
```
The two solutions are equivalent in terms of features, but the `async`/`await` might be a little bit overkill... You're telling that your function will return a Promise (mark it `async`), then you takes out the result of the promise by doing `await` on it. So you take the result out of a Promise to put it back in another Promise...


### usage
You need to `await` on the _auth_ function. Like I said earlier, _auth_ will return a Promise. So if you do `console.log(auth(ctx.... ))`, it will log `Promise <pending...>`. And the `if` will also test on a Promise rather than a value. So you can do the following for example:
```javascript
module.exports.auth = async function (ctx) {
  const user = await auth(ctx.request.body.email, ctx.request.body.password);
  console.log(user)
  if (user) {
    ctx.status = 200
  } else {
    ctx.set('Content-Type', 'text/plain')
    ctx.status = 401
    ctx.body = 'Wrong Login or Password'
  }
  return true
}
```
Here, contrarly to the precedent case (the _auth_ function), `async`/`await` help for the clarification of the code greatly.


### Side notes

In fact, the first function, you should use `const` instead of `let`, and if you take the path of the Promise (I highly recommend it), you can write the function in a simpler way:
```javascript
const auth = (email, password) =>
  models.users.filter({
    email: email,
    password: password,
  }).run()
```

**Comment by justinrlle** [comment]
Btw, about that part
```javascript
  } else {
    ctx.set('Content-Type', 'text/plain')
    ctx.status = 401
    ctx.body = 'Wrong Login or Password'
  }
```
You should here use the new `HttpError` class:
```javascript
throw new HttpError('Wrong Login or Password', 401)
```

**Comment by Shenrak** [comment]
You really should write *tutorials* mate.
